import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "background":                  "#0F1923",
        "surface":                     "#0F1923",
        "surface-dim":                 "#0F1923",
        "surface-container-lowest":    "#0f0e0b",
        "surface-container-low":       "#1c1c18",
        "surface-container":           "#20201b",
        "surface-container-high":      "#2b2a26",
        "surface-container-highest":   "#363530",
        "surface-bright":              "#3a3934",
        "surface-variant":             "#363530",
        "surface-tint":                "#ffb3b2",
        "on-surface":                  "#e6e2db",
        "on-surface-variant":          "#e4bdbc",
        "on-background":               "#e6e2db",
        "primary":                     "#FF4655",
        "primary-container":           "#ff525d",
        "on-primary":                  "#680013",
        "on-primary-fixed":            "#410008",
        "on-primary-container":        "#5b000f",
        "primary-fixed":               "#ffdad9",
        "primary-fixed-dim":           "#ffb3b2",
        "on-primary-fixed-variant":    "#92001f",
        "inverse-primary":             "#bd0c2d",
        "tertiary":                    "#00dbe9",
        "tertiary-container":          "#00a0aa",
        "tertiary-fixed":              "#7df4ff",
        "tertiary-fixed-dim":          "#00dbe9",
        "on-tertiary":                 "#00363a",
        "on-tertiary-container":       "#002f33",
        "on-tertiary-fixed":           "#002022",
        "on-tertiary-fixed-variant":   "#004f54",
        "secondary":                   "#bdc7d5",
        "secondary-container":         "#404a55",
        "secondary-fixed":             "#d9e3f2",
        "secondary-fixed-dim":         "#bdc7d5",
        "on-secondary":                "#27313c",
        "on-secondary-container":      "#afb9c7",
        "on-secondary-fixed":          "#121c27",
        "on-secondary-fixed-variant":  "#3e4853",
        "outline":                     "#ab8887",
        "outline-variant":             "#5b403f",
        "error":                       "#ffb4ab",
        "error-container":             "#93000a",
        "on-error":                    "#690005",
        "on-error-container":          "#ffdad6",
        "inverse-surface":             "#e6e2db",
        "inverse-on-surface":          "#31302c",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body:     ["Manrope", "sans-serif"],
        label:    ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        sm:      "0px",
        md:      "0px",
        lg:      "0px",
        xl:      "0px",
        "2xl":   "0px",
        full:    "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
